
export const MENU_DISHES = {
    breakfasts: [
        {
            id: 1,
            name: 'Омлет',
            category: 'breakfasts',
            price: 30,
            weight: '100 гр',
            description: 'Два гарно обсмажених курячих яйця',
        },
        {
            id: 2,
            name: 'Вівсяноблинчик',
            category: 'breakfasts',
            price: 95,
            weight: '350 гр',
            description: 'Вівсянка, яйце, молоко, червона риба та крем сир',
        },
        {
            id: 3,
            name: 'Панкейки',
            category: 'breakfasts',
            price: 55,
            weight: '3 шт/100 гр',
            description: 'Яйце, банан, борошно',
        },
        {
            id: 4,
            name: 'Овочевий салат',
            category: 'breakfasts',
            price: 35,
            weight: '150 гр',
            description:
                'Огірок свіжий, помідор, цибуля маринована, олія',
        },
    ],

    coldAppetizers: [
        {
            id: 5,
            name: 'Сирна тареля',
            category: 'coldAppetizers',
            price: 'від 30',
            weight: '100 гр',
            description: 'Залежить від обраного виду сиру',
        },
        {
            id: 6,
            name: 'М’ясна тареля',
            category: 'coldAppetizers',
            price: 'від 30',
            weight: '100 гр',
            description: 'Залежить від обраного виду сиру',
        },
        {
            id: 7,
            name: 'Домашня нарізка',
            category: 'coldAppetizers',
            price: 75,
            weight: '100 гр',
            description: 'Буженина, ковбаска домашня',
        },
        {
            id: 8,
            name: 'Сальце з гірчицею',
            category: 'coldAppetizers',
            price: 30,
            weight: '100 гр',
            description: 'Гірчиця міцна або французька',
        },
        {
            id: 9,
            name: 'Овочева палітра',
            category: 'coldAppetizers',
            price: 'від 20',
            weight: '100 гр',
            description: 'Огірок, помідор, перець болгарський',
        },
    ],

    salads: [
        {
            id: 10,
            name: 'Овочевий салат',
            category: 'salads',
            price: 25,
            weight: '150 гр',
            description: 'Капуста, морква, соняшникова олія',
        },
        {
            id: 11,
            name: 'Аля-цезар',
            category: 'salads',
            price: 350,
            weight: '',
            description:"Пекінська капуста, м'ясо курки, помідор, яйця, маслини, сухарики, сир пармезан, заправка на основі соєвого соусу",
        },
        {
            id: 12,
            name: 'Грецький',
            category: 'salads',
            price: 350,
            weight: '',
            description:
                'Огірок, помідор, перець солодкий, маслини, фета, цибуля, орегано, соус',
        },
        {
            id: 13,
            name: 'З лососем',
            category: 'salads',
            price: 420,
            weight: '',
            description:
                'Мікс салату, лосось, крем сир, соєвий соус, кунжут, заправка соєвий соус, олія та сік лимону',
        },
        {
            id: 14,
            name: 'Роксолана',
            category: 'salads',
            price: 400,
            weight: '',
            description:
                'М’ясо курки, морква корейська, ізюм, сухарики, маслини, цибуля маринована, кукурудза, заправка майонез',
        },
        {
            id: 15,
            name: 'Від Солохи',
            category: 'salads',
            price: 300,
            weight: '',
            description:
                'Молода капуста або пекінська, кукурудза, тунець, огірки',
        },
        {
            id: 16,
            name: 'Ноктюрн',
            category: 'salads',
            price: 350,
            weight: '',
            description:
                'Копчений окісток, смажені гриби, твердий сир, соковиті помідори, яйця, маринована цибуля, майонез.',
        },
        {
            id: 17,
            name: 'Фантазія',
            category: 'salads',
            price: 350,
            weight: '',
            description:
                'Шинка, цибуля маринована, яйця, сир твердий, кукурудза, ананаси, заправка майонез',
        },
        {
            id: 18,
            name: 'Грибна поляна',
            category: 'salads',
            price: 350,
            weight: '',
            description:
                'Мариновані шампіньони, зелена цибуля, картопля, плавлений сир, морква, м’ясо, заправка майонез',
        },
        {
            id: 19,
            name: 'Драна курка',
            category: 'salads',
            price: 340,
            weight: '',
            description:
                'М’ясо курки, морква корейська, гриби обсмажені, яйця, заправка майонезний соус',
        },
        {
            id: 20,
            name: 'Насолода',
            category: 'salads',
            price: 330,
            weight: '',
            description:
                'М’ясо курки, чорнослив, свіжий огірок, яйце, горіхи, заправка майонез',
        },
        {
            id: 21,
            name: 'Класична шуба',
            category: 'salads',
            price: 35,
            weight: '100гр',
            description:
                'Оселедець, цибуля, картопля, морква, яйце, буряк червоний, майонез',
        },
        {
            id: 22,
            name: 'Олів’є',
            category: 'salads',
            price: 400,
            weight: '1 кг',
            description:
                'Ковбаса варена, картопля, яйце, огірок, горошок, майонез',
        },
    ],

    firstDishes: [
        {
            id: 23,
            name: 'Український борщ',
            category: 'firstDishes',
            price: 30,
            weight: '300 г',
            description: '',
        },
        {
            id: 24,
            name: 'Солянка від Солохи',
            category: 'firstDishes',
            price: 60,
            weight: '300 г',
            description: '',
        },
        {
            id: 25,
            name: 'Окрошка',
            category: 'firstDishes',
            price: 60,
            weight: '300 г',
            description: '',
        },
    ],

    mainCourses: [
        {
            id: 26,
            name: 'Запечені реберця',
            category: 'mainCourses',
            price: 42,
            weight: '100 гр',
            description: 'Ребра, спеції',
        },
        {
            id: 27,
            name: 'Відбивна з курки',
            category: 'mainCourses',
            price: 80,
            weight: '',
            description: '',
        },
        {
            id: 28,
            name: 'Відбивна з свинини',
            category: 'mainCourses',
            price: 90,
            weight: '',
            description: '',
        },
        {
            id: 29,
            name: 'Котлета',
            category: 'mainCourses',
            price: 30,
            weight: '',
            description: '',
        },
    ],

    fishDishes: [
        {
            id: 30,
            name: 'Запечена скумбрія',
            category: 'fishDishes',
            price: 30,
            weight: '100 гр',
            description: 'Скумбрія, перець, помідори, морква, гриби',
        },
        {
            id: 31,
            name: 'Смажений хек',
            category: 'fishDishes',
            price: 30,
            weight: '100 гр',
            description: 'Борошно, спеції',
        },
        {
            id: 32,
            name: 'Хек під томатом',
            category: 'fishDishes',
            price: 150,
            weight: '',
            description: 'Хек, томати, морква, цибуля, смажений/печений, спеції',
        },
    ],

    sideDishes: [
        {
            id: 33,
            name: 'Тушена картопля',
            category: 'sideDishes',
            price: 30,
            weight: '250 гр',
            description: '',
        },
        {
            id: 34,
            name: 'Картопля по селянськи',
            category: 'sideDishes',
            price: 30,
            weight: '250 гр',
            description: '',
        },
        {
            id: 35,
            name: 'Картопля пюре',
            category: 'sideDishes',
            price: 30,
            weight: '250 г',
            description: '',
        },
        {
            id: 36,
            name: 'Гречана каша',
            category: 'sideDishes',
            price: 30,
            weight: '250 г',
            description: '',
        },
        {
            id: 37,
            name: 'Рис з м’ясом і овочами',
            category: 'sideDishes',
            price: 50,
            weight: '250 г',
            description: '',
        },
        {
            id: 38,
            name: 'Картопля фрі + соус',
            category: 'sideDishes',
            price: 45 + 15,
            weight: '150 г',
            description: '',
        },
    ],

    specialDishes: [
        {
            id: 39,
            name: 'Налисники з м’ясом',
            category: 'specialDishes',
            price: 35,
            weight: '1 шт',
            description: 'Свинина, морква, цибуля ріпчаста, спеції',
        },
        {
            id: 40,
            name: 'Налисники з солодким сиром',
            category: 'specialDishes',
            price: 25,
            weight: '1 шт',
            description: 'Мак або яблука на вибір',
        },
        {
            id: 41,
            name: 'Вареники з картоплею та шкварками',
            category: 'specialDishes',
            price: 50,
            weight: '6 шт',
            description: '',
        },
        {
            id: 42,
            name: 'Вареники з капустою',
            category: 'specialDishes',
            price: 50,
            weight: '6 шт',
            description: '',
        },
                {
            id: 80,
            name: 'Вареники з сиром',
            category: 'specialDishes',
            price: 80,
            weight: '6 шт',
            description: '',
        },
        {
            id: 43,
            name: "Галушки з м'ясом та шкварками",
            category: 'specialDishes',
            price: 50,
            weight: '6 шт',
            description: '',
        },
        {
            id: 44,
            name: 'Пельмені по домашньому',
            category: 'specialDishes',
            price: 50,
            weight: '1 пр',
            description: '',
        },
        {
            id: 45,
            name: 'Голубці',
            category: 'specialDishes',
            price: 25,
            weight: '1 шт',
            description: '',
        },
        {
            id: 46,
            name: 'Сирний рулет',
            category: 'specialDishes',
            price: 60,
            weight: '100 гр',
            description: 'Начинка крабове м’ясо, крем сир, яйце',
        },
        {
            id: 47,
            name: 'Шпинат рулет',
            category: 'specialDishes',
            price: 30,
            weight: '100 г',
            description: 'З сьомгою та крем сиром',
        },
        {
            id: 48,
            name: 'Деруни із сметаною',
            category: 'specialDishes',
            price: 50,
            weight: '1 пр',
            description: '',
        },
        {
            id: 49,
            name: 'Деруни в горщику',
            category: 'specialDishes',
            price: 85,
            weight: '',
            description: 'Соус сметанний, гриби, сир',
        }
    ],

    pizza: [
        {
            id: 51,
            name: 'Салямі',
            category: 'pizza',
            price: 200,
            weight: '30 см',
            description: 'Салямі, соус, огірок маринований, сир твердий',
        },
        {
            id: 52,
            name: 'Гавайська',
            category: 'pizza',
            price: 200,
            weight: '30 см',
            description: "М'ясо курки, ананаси, соус, сир",
        },
        {
            id: 53,
            name: 'З куркою та грибами',
            category: 'pizza',
            price: 200,
            weight: '30 см',
            description: "М'ясо курки, гриби, соус, сир, кукурудза за бажанням",
        },
        {
            id: 54,
            name: 'Чотири сири',
            category: 'pizza',
            price: 220,
            weight: '30 см',
            description: 'Сир голландський, сир моцарела, сир український, сир гауда',
        },
    ],

    additional: [
        {
            id: 55,
            name: 'Скибка білого хлібу',
            category: 'additional',
            price: 3,
            weight: '',
            description: '',
        },
        {
            id: 56,
            name: 'Скибка чорного хлібу',
            category: 'additional',
            price: 3,
            weight: '',
            description: '',
        },
        {
            id: 57,
            name: 'Сметана',
            category: 'additional',
            price: 10,
            weight: '50 гр',
            description: '',
        },
        {
            id: 58,
            name: 'Майонез',
            category: 'additional',
            price: 10,
            weight: '50 гр',
            description: '',
        },
        {
            id: 59,
            name: 'Томатний',
            category: 'additional',
            price: 10,
            weight: '50 гр',
            description: '',
        },
        {
            id: 60,
            name: 'Гірчиця',
            category: 'additional',
            price: 5,
            weight: '30 гр',
            description: '',
        },
        {
            id: 61,
            name: 'Соус соєвий',
            category: 'additional',
            price: 5,
            weight: '30 гр',
            description: '',
        },
    ],
    nonalcoholicdrinks:[
        {
            id: 64,
            name: 'Coca-Cola',
            category: 'nonalcoholicdrinks',
            price: 45,
            weight: '250 мл',
            description: '',
        },
        {
            id: 65,
            name: 'Лимонад',
            category: 'nonalcoholicdrinks',
            price: 15,
            weight: '250 мл',
            description: '',
        },
        {
            id: 66,
            name: 'Узвар',
            category: 'nonalcoholicdrinks',
            price: 15,
            weight: '250 мл',
            description: '',
        },
        
    ],
    alcohol:[
        {
            id: 70,
            name: 'Бренді Aznauri 3',
            category: 'alcohol',
            price: 26,
            weight: '50 мл',
            description: '',
        },
        {
            id: 71,
            name: 'Бренді Aznauri 4',
            category: 'alcohol',
            price: 26,
            weight: '50 мл',
            description: '',
        },
        {
            id: 72,
            name: 'Бренді Aznauri 5',
            category: 'alcohol',
            price: 31,
            weight: '50 мл',
            description: '',
        },
        {
            id: 73,
            name: 'Горілка класична',
            category: 'alcohol',
            price: 40,
            weight: '50 мл',
            description: '',
        },
        {
            id: 74,
            name: 'Вино біле напівсолодке',
            category: 'alcohol',
            price: 25,
            weight: '100 мл',
            description: '',
        },
        {
            id: 75,
            name: 'Вино червоне напівсолодке',
            category: 'alcohol',
            price: 25,
            weight: '100 мл',
            description: '',
        },
        {
            id: 76,
            name: 'Вино біле сухе',
            category: 'alcohol',
            price: 30,
            weight: '100 мл',
            description: '',
        },
    ],
    coctails:[
        {
            id: 80,
            name: 'Блакитна лагуна',
            category: 'coctails',
            price: 100,
            weight: '190 мл',
            description: 'Горілка, лікер Blue Curaçao, Sprite або лимонад, лід, часточка лимона',
        },
        {
            id: 81,
            name: 'Дайкірі',
            category: 'coctails',
            price: 150,
            weight: '100 мл',
            description: 'Білий ром, сік лайма, цукровий сироп',
        },
        {
            id: 82,
            name: 'Мохіто',
            category: 'coctails',
            price: 100,
            weight: '220 мл',
            description: "Білий ром, лайм, цукор або цукровий сироп, м'ята, содова, лід",
        },
        {
            id: 83,
            name: 'Маргарита',
            category: 'coctails',
            price: 150,
            weight: '100 мл',
            description: 'Текіла, Triple Sec, сік лайма, сіль для обідка',
        },
        {
            id: 84,
            name: 'Куба Лібре',
            category: 'coctails',
            price: 150,
            weight: '180 мл',
            description: 'Білий ром, Coca-Cola, сік лайма, лід',
        },
        {
            id: 85,
            name: 'Блакитна Маргарита',
            category: 'coctails',
            price: 150,
            weight: '100 мл',
            description: 'Текіла, Blue Curaçao, сік лайма',
        },
        {
            id: 86,
            name: "Текіла Б'янко",
            category: 'coctails',
            price: 170,
            weight: '90 мл',
            description: 'Срібна текіла, Triple Sec, сік лайма, лід',
        },
        {
            id: 87,
            name: 'Неоновий Ліс',
            category: 'coctails',
            price: 180,
            weight: '180 мл',
            description: 'Джин, лікер Green Mint, яблучний сік, сік лайма, лід',
        },
        {
            id: 88,
            name: 'Віскі Сауер',
            category: 'coctails',
            price: 200,
            weight: '115 мл',
            description: 'Бурбон або віскі, лимонний сік, цукровий сироп, яєчний білок',
        },
        {
            id: 89,
            name: 'Зелений Веспер',
            category: 'coctails',
            price: 150,
            weight: '85 мл',
            description: 'Джин, горілка, сухий вермут, лікер Green Mint або Green Chartreuse',
        },
        {
            id: 90,
            name: 'Галактика',
            category: 'coctails',
            price: 150,
            weight: '190 мл',
            description: 'Джин, сироп Blue Curaçao, малиновий сироп, Sprite або тонік, кандурин',
        },
    ],
    Shot:[
        {
            id: 100,
            name: 'Камікадзе',
            category: 'Shot',
            price: 100,
            weight: '50 мл',
            description: 'Горілка, Triple Sec, сік лайма',
        },
        {
            id: 101,
            name: 'Зелений мексиканець',
            category: 'Shot',
            price: 100,
            weight: '50 мл',
            description: 'Текіла Silver, лікер Pisang Ambon (або банановий лікер), лимонний сік',
        },
        {
            id: 101,
            name: 'Хіросіма',
            category: 'Shot',
            price: 100,
            weight: '50 мл',
            description: 'Самбука, Baileys, абсент, гренадин',
        },
        {
            id: 102,
            name: 'Текіла Бум',
            category: 'Shot',
            price: 100,
            weight: '50 мл',
            description: 'Текіла, Sprite або тонік',
        },
        {
            id: 103,
            name: 'Самбука',
            category: 'Shot',
            price: 100,
            weight: '50 мл',
            description: '',
        },
        {
            id: 104,
            name: 'Б - 52',
            category: 'Shot',
            price: 120,
            weight: '50 мл',
            description: 'Кавовий лікер, Baileys, Triple Sec',
        },
        {
            id: 103,
            name: 'Б - 53',
            category: 'Shot',
            price: 120,
            weight: '50 мл',
            description: 'Кавовий лікер, Baileys, самбука (або абсент)',
        }
       
    ]        
};



export const MENU_CATEGORIES = [
    {
        id: 'breakfasts',
        href: '#breakfasts',
        text: 'Сніданки',
        bgImage: '/img/beackground/snidanok.webp',
    },
    {
        id: 'coldAppetizers',
        href: '#coldAppetizers',
        text: 'Холодні закуски',
        bgImage: '/img/beackground/holodnizakusky.webp',
    },
    {
        id: 'salads',
        href: '#salads',
        text: 'Салати',
        bgImage: '/img/beackground/salad.webp',
    },
    {
        id: 'firstDishes',
        href: '#firstDishes',
        text: 'Перші страви',
        bgImage: '/img/beackground/fistdish.webp',
    },
    {
        id: 'mainCourses',
        href: '#mainCourses',
        text: 'Основні страви',
        bgImage: '/img/beackground/maindish.webp',
    },
    {
        id: 'fishDishes',
        href: '#fishDishes',
        text: 'Страви з риби',
        bgImage: '/img/beackground/dishfish.webp',
    },
    {
        id: 'sideDishes',
        href: '#sideDishes',
        text: 'Гарніри',
        bgImage: '/img/beackground/garniry.webp',
    },
    {
        id: 'specialDishes',
        href: '#specialDishes',
        text: 'Особливі страви',
        bgImage: '/img/beackground/spycificaldish.webp',
    },
    {
        id: 'pizza',
        href: '#pizza',
        text: 'Піца',
        bgImage: '/img/beackground/picca.webp',
    },
    {
        id: 'additional',
        href: '#additional',
        text: 'Додатково',
        bgImage: '/img/beackground/dodatkovo.webp'
    },
        {
        id: 'nonalcoholicdrinks',
        href: '#nonalcoholicdrinks',
        text: 'Напої б/a',
        bgImage: '/img/beackground/non-alcoholicdrinks.webp'
    },
        {
        id: 'alcohol',
        href: '#alcohol',
        text: 'Алкоголь',
        bgImage: '/img/beackground/alcohol.webp'
    },
        {
        id: 'coctails',
        href: '#coctails',
        text: 'Коктейлі',
        bgImage: '/img/beackground/kokteil.webp'
    },
    {
        id: 'Shot',
        href: '#Shot',
        text: 'Шоти',
        bgImage: '/img/beackground/shots.webp'
    },
];
